Repository 2022-DKUS-Summer-Study/Data-Structure, pull requests merged in 2022-07, with the labels that each got.

#13 restore : mistake merge
  윤영은/1주차/array_1.c
  윤영은/1주차/array_1.h
  윤영은/1주차/main_1.c
Labels: 수정 후 PR 업데이트

#15 구현모 자료구조 1주차 과제 제출
  현모/1주차/README.md
  현모/1주차/array_sample.c
  현모/1주차/array_sample.h
  현모/1주차/main.c
Labels: 수정 후 PR 업데이트, 과제 제출

#26 구예원 1주차 과제 제출
  예원/1주차/README.md
  예원/1주차/array.c
  예원/1주차/array.h
  예원/1주차/summerStudy_1.c
  예원/1주차/summerStudy_1.sln
Labels: 과제 제출

#24 김다은 자료구조 2주차 과제 제출
  Dara-Kim/0주차/0주차 과제.c
  Dara-Kim/1주차/array.c
  Dara-Kim/1주차/array.h
  Dara-Kim/1주차/main.c
  Dara-Kim/2주차/README.md
Labels: 과제 제출, Quiz, 보류

#22 윤영은 자료구조 2주차 과제 제출
  윤영은/2주차/README.md
  윤영은/2주차/linked_list_2.c
  윤영은/2주차/linked_list_2.h
  윤영은/2주차/main_2.c
Labels: 과제 제출

#23 구현모 자료구조 2주차 과제 제출
  현모/2주차/README.md
  현모/2주차/linked_list_sample.c
  현모/2주차/linked_list_sample.h
  현모/2주차/main.c
Labels: 수정 후 PR 업데이트, 과제 제출
